// Generated by CoffeeScript 1.8.0

/*
 * weather 接口类型枚举
 */

(function() {
  var TYPE_FORECAST3D, TYPE_INDEX, TYPE_OBSERVE;

  TYPE_INDEX = 'index';

  TYPE_FORECAST3D = 'forecast3d';

  TYPE_OBSERVE = 'observe';

  module.exports = {
    TYPE_INDEX: TYPE_INDEX,
    TYPE_FORECAST3D: TYPE_FORECAST3D,
    TYPE_OBSERVE: TYPE_OBSERVE
  };

}).call(this);
