// Generated by CoffeeScript 1.7.1

/*
 * 简单的借口实现
 */

(function() {
  var SimpleWeather, areaid_f, areaid_v, assert, debulg, fs, path, root_path;

  debulg = require('debug')("node-weather::simple");

  assert = require('assert');

  path = require('path');

  fs = require('fs');

  root_path = path.resolve(__dirname, "../");

  areaid_v = null;

  areaid_f = null;

  SimpleWeather = (function() {
    function SimpleWeather(appId, privateKey) {
      this.appId = appId;
      this.privateKey = privateKey;
      assert(this.appId, "missing appId");
      assert(this.privateKey, "missing privateKey");
      if (areaid_f == null) {
        console.log("bbbbbbbbbbbb");
        areaid_f = JSON.parse(fs.readFileSync(path.join(root_path, "./lib/jsons/areaid_f.json")));
      }
      if (areaid_v == null) {
        areaid_v = JSON.parse(fs.readFileSync(path.join(root_path, "./lib/jsons/areaid_v.json")));
      }
    }

    return SimpleWeather;

  })();

}).call(this);
