// Generated by CoffeeScript 1.8.0

/*
 * 简单的借口实现
 */

(function() {
  var SimpleWeather, areaid_f, areaid_v, assert, debuglog, fs, http, path, request, root_path, sign, types;

  debuglog = require('debug')("node-weather::simple");

  assert = require('assert');

  path = require('path');

  fs = require('fs');

  http = require('http');

  sign = require('./utils/sign');

  request = require('request');

  types = require('./enums/types');

  root_path = path.resolve(__dirname, "../");

  areaid_v = null;

  areaid_f = null;

  SimpleWeather = (function() {
    function SimpleWeather(url, appId, privateKey) {
      this.url = url;
      this.appId = appId;
      this.privateKey = privateKey;
      assert(this.url, "missing url");
      assert(this.appId, "missing appId");
      assert(this.privateKey, "missing privateKey");
      debuglog("instantiation");
      if (areaid_f == null) {
        areaid_f = JSON.parse(fs.readFileSync(path.join(root_path, "./lib/jsons/areaid_f.json")));
      }
      if (areaid_v == null) {
        areaid_v = JSON.parse(fs.readFileSync(path.join(root_path, "./lib/jsons/areaid_v.json")));
      }
    }

    SimpleWeather.prototype.loadAreaidF = function() {
      return areaid_f;
    };

    SimpleWeather.prototype.loadAreaidV = function() {
      return areaid_v;
    };

    SimpleWeather.prototype.loadAreaById = function(areaid) {
      return areaid_v[areaid];
    };

    SimpleWeather.prototype.loadIndex = function(areaid, callback) {
      this.loadByType(areaid, types.TYPE_INDEX, callback);
    };

    SimpleWeather.prototype.loadForecast3d = function(areaid, callback) {
      this.loadByType(areaid, types.TYPE_FORECAST3D, callback);
    };

    SimpleWeather.prototype.loadObserver = function(areaid, callback) {
      this.loadByType(areaid, types.TYPE_OBSERVE, callback);
    };

    SimpleWeather.prototype.loadByType = function(areaid, type, callback) {
      var date, key, options, public_key, url;
      assert(areaid, "missing areaid");
      assert(type, "missing type");
      date = new Date().Format("yyyyMMddhhmm");
      public_key = "" + this.url + "?areaid=" + areaid + "&type=" + type + "&date=" + date + "&appid=" + this.appId;
      key = sign.sign(public_key, this.privateKey);
      url = "" + this.url + "?areaid=" + areaid + "&type=" + type + "&date=" + date + "&appid=" + (this.appId.substr(0, 6)) + "&key=" + (sign.urlEncode(key));
      options = {
        url: url,
        method: "GET"
      };
      request(url, function(err, res, body) {
        if (err != null) {
          callback(err);
        }
        callback(null, body);
      });
    };

    return SimpleWeather;

  })();

  module.exports = SimpleWeather;

}).call(this);
