// Generated by CoffeeScript 1.8.0

/*
 * excel 2 json 的测试类
 */

(function() {
  var debuglog, excel2Coffee, excel2json, path, root_path, should;

  should = require("should");

  excel2json = require("../utils/excel2json");

  excel2Coffee = require("../utils/excel2Coffee");

  path = require('path');

  debuglog = require("debug")("node-weather::tests::excel2json_test");

  root_path = path.resolve(__dirname, "../../");

  describe("test excel2json", function() {
    before(function() {});
    return describe("parseFile", function() {
      it("parseFile test", function(done) {
        this.timeout(5000);
        console.log(root_path);
        return excel2json.parseFile(path.join(root_path, 'areaid_f.xlsx'), path.join(root_path, './lib/jsons/areaid_f.json'), function(err) {
          return done();
        });
      });
      it("parseFile test2", function(done) {
        this.timeout(5000);
        console.log(root_path);
        return excel2json.parseFile(path.join(root_path, 'areaid_v.xlsx'), path.join(root_path, './lib/jsons/areaid_v.json'), function(err) {
          return done();
        });
      });
      it("parseFile test", function(done) {
        this.timeout(5000);
        console.log(root_path);
        return excel2Coffee.parseFile(path.join(root_path, 'areaid_f.xlsx'), path.join(root_path, './src/enums/areaid_f.coffee'), function(err) {
          return done();
        });
      });
      return it("parseFile test2", function(done) {
        this.timeout(5000);
        console.log(root_path);
        return excel2Coffee.parseFile(path.join(root_path, 'areaid_v.xlsx'), path.join(root_path, './src/enums/areaid_v.coffee'), function(err) {
          return done();
        });
      });
    });
  });

}).call(this);
