// Generated by CoffeeScript 1.7.1

/*
 * utils::sign 的测试类
 */

(function() {
  var debuglog, private_key, should, sign;

  should = require("should");

  sign = require("../utils/sign");

  debuglog = require("debug")("node-weather::tests::sign_test");

  private_key = 'dsafasdfafafas';

  describe("test sign", function() {
    before(function() {});
    return describe("sign", function() {
      it("sign test", function(done) {
        var text;
        text = sign.sign('http://dsjkdjsfkjaskdjak', private_key);
        console.log(text);
        return done();
      });
      return it("sign test 2", function(done) {
        var public_key;
        public_key = "http://open.weather.com.cn/data/?areaid=101010100&type=index_f&date=201212010741&appid=1234567890";
        private_key = "793ffb_SmartWeatherAPI_662cbc7";
        return console.log(sign.sign(public_key, private_key));
      });
    });
  });

}).call(this);
