// Generated by CoffeeScript 1.8.0
(function() {
  var SimpleWeather, appId, config, debuglog, httpUrl, privateKey, should, types;

  should = require("should");

  debuglog = require("debug")("node-weather::tests::simple_test");

  SimpleWeather = require('../index').SimpleWeather;

  types = require('../enums/types');

  config = require('./config');

  httpUrl = config.httpUrl;

  appId = config.appId;

  privateKey = config.privateKey;

  describe("test simple", function() {
    before(function() {});
    describe("constructor", function() {
      it("loadByType 指数 index test", function(done) {
        var sw;
        this.timeout = 30000;
        sw = new SimpleWeather(httpUrl, appId, privateKey);
        return sw.loadByType('101010100', types.TYPE_INDEX, function(err, body) {
          if (err != null) {
            console.log(err);
          }
          console.dir(body);
          return done();
        });
      });
      it("loadByType 常规预报： forecast3d test", function(done) {
        var sw;
        this.timeout = 30000;
        sw = new SimpleWeather(httpUrl, appId, privateKey);
        return sw.loadByType('101010100', types.TYPE_FORECAST3D, function(err, body) {
          if (err != null) {
            console.log(err);
          }
          console.dir(body);
          return done();
        });
      });
      return it("loadByType 实况： observe test", function(done) {
        var sw;
        this.timeout = 30000;
        sw = new SimpleWeather(httpUrl, appId, privateKey);
        return sw.loadByType('101010100', types.TYPE_OBSERVE, function(err, body) {
          if (err != null) {
            console.log(err);
          }
          console.dir(body);
          return done();
        });
      });
    });
    return describe("load weather by type", function() {
      it("loadByType 指数 index test", function(done) {
        var sw;
        this.timeout = 30000;
        sw = new SimpleWeather(httpUrl, appId, privateKey);
        return sw.loadIndex('101010100', function(err, body) {
          if (err != null) {
            console.log(err);
          }
          console.dir(body);
          return done();
        });
      });
      it("loadByType 常规预报： forecast3d test", function(done) {
        var sw;
        this.timeout = 30000;
        sw = new SimpleWeather(httpUrl, appId, privateKey);
        return sw.loadForecast3d('101010100', function(err, body) {
          if (err != null) {
            console.log(err);
          }
          console.dir(body);
          return done();
        });
      });
      return it("loadByType 实况： observe test", function(done) {
        var sw;
        this.timeout = 30000;
        sw = new SimpleWeather(httpUrl, appId, privateKey);
        return sw.loadObserver('101010100', function(err, body) {
          if (err != null) {
            console.log(err);
          }
          console.dir(body);
          return done();
        });
      });
    });
  });

}).call(this);
